name: Auto-Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  # Basic code checks
  check:
    name: Basic Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check Python syntax
      run: |
        python -m py_compile backend.py
        python -m py_compile front.py
        echo "✅ Syntax check passed!"
    
    - name: Check imports
      run: |
        python -c "import backend" 2>/dev/null && echo "✅ Backend imports OK" || echo "⚠️ Backend import warning"
        echo "✅ Import check completed!"

  # Auto-merge the PR
  auto-merge:
    name: Auto Merge
    needs: check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Auto-approve PR
      uses: hmarr/auto-approve-action@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Auto-merge PR
      uses: pascalgn/automerge-action@v0.16.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MERGE_LABELS: ""
        MERGE_METHOD: "squash"
        MERGE_COMMIT_MESSAGE: "pull-request-title"
        MERGE_REMOVE_LABELS: ""
        MERGE_FORKS: "false"
